apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: girus-cluster-rolebinding
  labels:
    {{- include "girus.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: girus-sa
    namespace: {{ include "girus.namespace" . }}
roleRef:
  kind: ClusterRole
  name: girus-cluster-role
  apiGroup: rbac.authorization.k8s.io
