apiVersion: apps/v1
kind: Deployment
metadata:
  name: girus-backend
  namespace: {{ include "girus.namespace" . }}
  labels:
    {{- include "girus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.backend.replicas }}
  selector:
    matchLabels:
      app: girus-backend
  template:
    metadata:
      labels:
        app: girus-backend
        {{- include "girus.labels" . | nindent 8 }}
    spec:
      serviceAccountName: girus-sa
      containers:
        - name: backend
          image: {{ .Values.deployment.backend.image | default "linuxtips/girus-backend:latest" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.deployment.backend.containerPort }}
          env:
            - name: PORT
              value: "8080"
            - name: GIN_MODE
              value: "release"
            - name: LAB_DEFAULT_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: girus-config
                  key: lab.defaultImage
                  optional: true
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /api/v1/health
              port: {{ .Values.deployment.backend.containerPort }}
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            httpGet:
              path: /api/v1/health
              port: {{ .Values.deployment.backend.containerPort }}
          resources:
            requests:
              memory: 256Mi
              cpu: 0.5
            limits:
              memory: 512Mi
              cpu: 1
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: girus-config
      {{- if .Values.deployment.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecretsName }}
      {{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: girus-frontend
  namespace: {{ include "girus.namespace" . }}
  labels:
    {{- include "girus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.frontend.replicas }}
  selector:
    matchLabels:
      app: girus-frontend
  template:
    metadata:
      labels:
        app: girus-frontend
        {{- include "girus.labels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ .Values.deployment.frontend.image | default "linuxtips/girus-frontend:latest" }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.deployment.frontend.containerPort }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              memory: 256Mi
              cpu: 0.5
            limits:
              memory: 512Mi
              cpu: 1
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      {{- if .Values.deployment.imagePullSecretsName }}
      imagePullSecrets:
        - name: {{ .Values.deployment.imagePullSecretsName }}
      {{ end }}
