---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-egress
  namespace: {{ include "girus.namespace" . }}
spec:
  policyTypes:
    - Ingress
    - Egress
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-egress
  namespace: {{ include "girus.namespace" . }}
spec:
  policyTypes:
    - Egress
  podSelector: {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ include "girus.namespace" . }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-ingress-coredns
  namespace: {{ include "girus.namespace" . }}
spec:
  policyTypes:
    - Egress
  podSelector: {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backend-ingress-kube-apiserver
  namespace: {{ include "girus.namespace" . }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      app: girus-backend
  egress:
    - to:
        - ipBlock:
            cidr: "172.18.0.2/24" # TODO: resolver Warning: spec.egress[0].to[0].ipBlock.cidr: CIDR value "172.18.0.2/24" is ambiguous in this context (should be "172.18.0.0/24" or "172.18.0.2/32"?) 
      ports:
        - port: 6443
          protocol: TCP
        - port: 443
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-ingress-backend
  namespace: {{ include "girus.namespace" . }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: girus-backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: girus-frontend
      ports:
        - port: {{ .Values.deployment.backend.port }}
          protocol: TCP
---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-nginx-ingress-frontend
  namespace: {{ include "girus.namespace" . }}
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: girus-frontend
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
          podSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
      ports:
        - port: {{ .Values.deployment.frontend.port }}
          protocol: TCP
{{ end }}
