apiVersion: v1
kind: Service
metadata:
  name: girus-backend
  namespace: {{ include "girus.namespace" . }}
spec:
  selector:
    app: girus-backend
  ports:
    - port: {{ .Values.deployment.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: girus-frontend
  namespace: {{ include "girus.namespace" . }}
spec:
  selector:
    app: girus-frontend
  ports:
    - port: {{ .Values.deployment.frontend.port }}
