namespaceOverride: ""

label:
  partOf: girus

deployment:
  backend:
    image: eduardothums/girus:backend-v1.0.1
    containerPort: 8080
    replicas: 1
  frontend:
    image: eduardothums/girus:frontend-v1.0.8
    containerPort: 8080
    replicas: 1
  imagePullSecretsName: ""

ingress:
  enabled: false
