namespaceOverride: ""

deployment:
  backend:
    # image: eduardothums/girus:backend-v1.0.0@sha256:fd0ab0a903e16f5e43197c10d6dc3f2e48d7855ae551730aa22899ef977ef3a9
    image: girus-backend:1
    port: 8080
    replicas: 1
  frontend:
    # image: eduardothums/girus:frontend-v1.0.5@sha256:84d3847d6ac16f0c09cfdb52125fbff3adb91c75ae2810c42255885fb30fbc99
    image: eduardothums/girus:frontend-v1.0.5
    port: 80
    replicas: 1
  imagePullSecretsName: ""

ingress:
  enabled: false
