namespaceOverride: ""

label:
  partOf: girus

deployment:
  backend:
    image: eduardothums/girus:backend-v1.0.4
    containerPort: 8080
    replicas: 1
  frontend:
    image: eduardothums/girus:frontend-v1.0.13
    containerPort: 8080
    replicas: 1
  imagePullSecretsName: ""

ingress:
  enabled: false
  external: false
