name: Release Charts

on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - "charts/**"
  # workflow_dispatch: {}

jobs:
  package-helm-chart:
    permissions:
      contents: write
      packages: write

    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      # - name: Set environment variables
      #   id: set-variables
      #   run: |
      #     echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
      #     echo "VERSION=$(yq -r .version ./charts/girus/Chart.yaml)" >> "$GITHUB_OUTPUT"          

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ github.token }}

      # - name: Package and push helm chart
      #   run: |
      #     helm package ./charts/girus
      #     helm push ./girus-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts          

      - name: Generate example template manifest
        run: helm template --namespace girus charts/girus > manifest.yaml

      - name: Create release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2.2.2
        with:
          files: manifest.yaml

  deploy-oke:
    # permissions:
    #   contents: write
    #   packages: write
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    needs: package-helm-chart
    # if: github.event_name == 'workflow_dispatch'

    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.5.0
        id: test-configure-kubectl-oke-action
        with:
          cluster: ${{ secrets.OKE_CLUSTER_OCID }}

      - name: Add helm repo
        run: helm repo add --force-update giropops-senhas https://eduardothums.github.io/giropops-helm-repo
       
      - name: Install/upgrade release
        run: helm upgrade --install --namespace giropops --create-namespace giropops-senhas giropops-senhas/giropops-senhas
      
      - name: Install/upgrade release
        run: kubectl get pod --namespace giropops
