name: Release Charts

on:
  push:
    branches:
      - main
    # paths:
    #   - "charts/**"

jobs:
  package-helm-chart:
    permissions:
      contents: read
      packages: write

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(yq -r .version ./charts/girus/Chart.yaml)" >> "$GITHUB_OUTPUT"          

      # - name: Env variable output
      #   id: test-variables
      #   run: |
      #     echo ${{ steps.set-variables.outputs.REPOSITORY }}
      #     echo ${{ steps.set-variables.outputs.VERSION }}          

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Package and push helm chart
        run: |
          helm package ./charts/girus
          helm push ./girus-${{ steps.set-variables.outputs.VERSION }}.tgz oci://${{ steps.set-variables.outputs.REPOSITORY }}/charts          

# jobs:
#   release:
#     runs-on: self-hosted

#     permissions:
#       contents: write
#     # runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
#         with:
#           fetch-depth: 0

#       - name: Configure Git
#         run: |
#           git config user.name "$GITHUB_ACTOR"
#           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

#       - name: Run chart-releaser
#         uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
#         env:
#           CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
