name: Validate the chart templates

on:
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  trivy-scan-code:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
        with:
          scan-type: config
          exit-code: '1'

  lint:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          fetch-depth: 0

      - name: Lint helm charts
        shell: bash
        run: find charts -type f -name Chart.yaml -exec dirname {} \; | xargs -I {} helm lint --strict {}
